name: demo-cd

on:
  push:
    branches: [gh-deploy]

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        name: Use node ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: "apps/demo"

      - name: Install Dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build --filter=@dzangolab/vue3-demo
        env:
          VITE_API_BASE_URL: "https://api.monorepo.dzangolab.org"
          VITE_APP_VERSION: ${{ steps.package-version.outputs.current-version}}
          VITE_APP_BUILD: 'develop'
          VITE_I18N_FALLBACK_LOCALE: 'en'
          VITE_I18N_LOCALES: 'en,fr'
          VITE_APP_TITLE: 'Dzangolab Vue3 Demo App'
          VITE_APP_SLUG: 'dzangolab-vue3'
          VITE_COPYRIGHT_HOLDER: 'Dzango Technologies Limited'
          VITE_COPYRIGHT_HOLDER_URL: 'https://dzango.com'
          VITE_FEATURE_SHOW_VERSION: '1'
          VITE_I18N_FALLBACK_LOCALE: 'en'
          VITE_I18N_LOCALES: 'en,fr'
          VITE_REDIRECT_IN: '10'
          VITE_SENTRY_DSN: 'TBD'
          VITE_SENTRY_ENABLED: 'false'
          VITE_SENTRY_ENVIRONMENT: 'develop'
          VITE_USER_PASSWORD_MIN_LENGTH: '10'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: apps/demo/dist
          token: ${{ secrets.GITHUB_TOKEN }}
